### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by frstich** [Metim0l/VisionCraft#1]
node textimage
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'C:\Users\xxx\textimage'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.8.0

im using the api and yes i subscribed on telegram, it seems that the modules are not integrated in the api or something is wrong, since i tried on the website it works good but not on the api that i get from the telegram.

to make sure that the problem was not from my code i literaly copied the example code you provided and i added the api i got from telegram and i get the same error

**Comment by Metim0l** [comment]
Ensure that you've installed the 'textimage' module by running npm install textimage or yarn add textimage in your project directory.

The Python example works very well. The JS example was not written by me, but by chatgpt, so there may be errors in it.

**Comment by Metim0l** [comment]
Ensure that you've installed the 'textimage' module by running npm install textimage or yarn add textimage in your project directory.

The Python example works very well. The JS example was not written by me, but by chatgpt, so there may be errors in it.

**Comment by Metim0l** [comment]
Ensure that you've installed the 'textimage' module by running npm install textimage or yarn add textimage in your project directory.

The Python example works very well. The JS example was not written by me, but by chatgpt, so there may be errors in it.

I'm sorry, I don't know JS, so an example for this programming language was written by chatgpt.

**Comment by Metim0l** [comment]
Ensure that you've installed the 'textimage' module by running npm install textimage or yarn add textimage in your project directory.

The Python example works very well. The JS example was not written by me, but by chatgpt, so there may be errors in it.

I'm sorry, I don't know JS, so an example for this programming language was written by chatgpt.

**Comment by frstich** [comment]
I tried the js code

**Comment by Metim0l** [comment]
I'm very sorry. There were problems with the API. Now I fixed everything, everything works.

**Comment by Metim0l** [comment]
You can copy the code from the example and replace the key with your own. Everything will work.
